<?php

namespace App\Jobs;

use App\Models\Draft;
use App\Models\Rule;
use App\Models\ScheduledPost;
use App\Services\AI\AIProviderFactory;
use App\Services\AI\PromptBuilderService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class GenerateContentJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 3;
    public $timeout = 300;
    public $backoff = [120, 600]; // 2 mins, then 10 mins

    public function __construct(public Rule $rule)
    {
    }

    public function handle(PromptBuilderService $promptBuilder): void
    {
        $topic = $this->rule->topics()->inRandomOrder()->first();
        $topicText = $topic ? $topic->topic : $this->rule->topic;

        $prompt = $promptBuilder->build($this->rule, $topic);
        $aiModel = $this->rule->aiModel;

        \Illuminate\Support\Facades\Log::info('GenerateContentJob started for Rule: ', $this->rule->toArray());

        try {
            // AI দিয়ে content তৈরি করো
            $provider = AIProviderFactory::make($aiModel);
            $content  = $provider->generate($prompt);

            // Remove <think> tags and their contents (generated by reasoning models like DeepSeek-R1)
            $content = preg_replace('/<think>.*?<\/think>\s*/s', '', $content);
            $content = trim($content);
            
            // Clean markdown json blocks if any
            $content = preg_replace('/^```json\s*/i', '', $content);
            $content = preg_replace('/\s*```$/', '', $content);
            $content = trim($content);
            
            $json = json_decode($content, true);
            
            if (json_last_error() === JSON_ERROR_NONE && is_array($json)) {
                if ($this->rule->format === 'poll' && isset($json['question']) && isset($json['options'])) {
                    $content = $json['question'] . "\n" . implode("\n", $json['options']);
                } else {
                    $content = $json['content'] ?? $content;
                }
            }

            if (empty($content)) {
                throw new \Exception('AI returned empty content.');
            }

            $contentHash = hash('sha256', $content);

            // Duplicate check
            $duplicate = Draft::where('content_hash', $contentHash)
                ->where('channel_id', $this->rule->channel_id)
                ->exists();

            if ($duplicate) {
                // If duplicate, throw exception to trigger queue backoff & retry
                // Do not mark as failed immediately unless it's the last attempt.
                throw new \Exception('Duplicate content detected. Regenerating in next attempt.');
            }

            // Draft সফল — create Draft
            $estimatedTokens = (int) round((str_word_count($prompt) + str_word_count($content)) * 1.33);
            
            $draft = Draft::create([
                'rule_id'        => $this->rule->id,
                'channel_id'     => $this->rule->channel_id,
                'ai_model_id'    => $aiModel->id,
                'topic_used'     => $topicText,
                'format'         => $this->rule->format,
                'status'         => 'draft',
                'content'        => $content,
                'content_hash'   => $contentHash,
                'ai_tokens_used' => $estimatedTokens,
            ]);

            // Notify Admin via System Telegram Bot
            $this->notifyAdminForApproval($draft);

            // Topic use count আপডেট করো
            if ($topic) {
                $topic->increment('use_count');
                $topic->update(['last_used_at' => now()]);
            }

        } catch (\Exception $e) {
            // Log the error
            \Illuminate\Support\Facades\Log::error('AI Generation Failed: ' . $e->getMessage(), [
                'rule_id' => $this->rule->id,
                'topic' => $topicText
            ]);

            if ($this->attempts() >= $this->tries) {
                // If it's the last attempt and still failing, save it as a failed draft
                Draft::create([
                    'rule_id'      => $this->rule->id,
                    'channel_id'   => $this->rule->channel_id,
                    'ai_model_id'  => $aiModel->id,
                    'topic_used'   => $topicText,
                    'format'       => $this->rule->format,
                    'status'       => 'failed',
                    'content'      => '',
                    'content_hash' => '',
                    'fail_reason'  => $e->getMessage(),
                ]);
                
                $botToken = \App\Models\Setting::get('system_bot_token');
                $adminChatId = \App\Models\Setting::get('admin_chat_id');
                if ($botToken && $adminChatId) {
                    \Illuminate\Support\Facades\Http::post("https://api.telegram.org/bot{$botToken}/sendMessage", [
                        'chat_id' => $adminChatId,
                        'text' => "❌ *AI Generation Failed*\n\n*Rule:* {$this->rule->name}\n*Reason:* " . $e->getMessage(),
                        'parse_mode' => 'Markdown',
                    ]);
                }
            }

            throw $e; // Queue retry-এর জন্য re-throw করো
        }
    }

    private function notifyAdminForApproval(Draft $draft): void
    {
        $botToken = \App\Models\Setting::get('system_bot_token');
        $chatId = \App\Models\Setting::get('admin_chat_id');

        if (!$botToken || (!$chatId)) {
            \Illuminate\Support\Facades\Log::warning("System Bot Token or Admin Chat ID missing. Draft #{$draft->id} is pending but no notification sent.");
            return;
        }

        $message = "📝 <b>New AI Draft Pending Approval!</b>\n";
        $message .= "<b>Channel:</b> {$draft->channel->title}\n";
        $message .= "<b>Rule:</b> {$draft->rule->name}\n\n";
        $message .= "<i>Content Preview:</i>\n" . mb_substr($draft->content, 0, 500) . (mb_strlen($draft->content) > 500 ? '...' : '') . "\n\n";
        $message .= "👉 Choose an option below, or reply with a custom time (e.g. 05:30 PM)";

        $keyboard = [
            'inline_keyboard' => [
                [
                    ['text' => '✅ Post Now', 'callback_data' => "approve_now:{$draft->id}"],
                    ['text' => '⏳ Post in 30 M', 'callback_data' => "approve_30m:{$draft->id}"],
                ],
                [
                    ['text' => '⏳ Post in 1 H', 'callback_data' => "approve_1h:{$draft->id}"],
                    ['text' => '❌ Reject', 'callback_data' => "reject:{$draft->id}"],
                ]
            ]
        ];

        \Illuminate\Support\Facades\Http::post("https://api.telegram.org/bot{$botToken}/sendMessage", [
            'chat_id' => $chatId,
            'text' => $message,
            'parse_mode' => 'HTML',
            'reply_markup' => json_encode($keyboard)
        ]);
    }
}
